package com.tuprofe.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;

/**
 *
 * @author diego
 */
@DynamoDBTable(tableName = "admin-user")
public class AdminUser extends User implements Serializable {

    public AdminUser() {
        super();
    }

    public AdminUser(String name, String lastName, String email, String password) {
        this();
        this.name = name;
        this.lastName = name;
        this.email = email;
        this.password = password;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @Override
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "name")
    @Override
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "state")
    @Override
    public Integer getState() {
        return state;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    @Override
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute(attributeName = "email")
    @Override
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute(attributeName = "password")
    @Override
    public String getPassword() {
        return password;
    }

}
