/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tuprofe.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author diego
 */
@DynamoDBTable(tableName = "interview")
public class Induction implements Serializable{
    private String id;
    private Long startDateTime;
    private Integer capacity;
    private Integer duration;
    private List<String> assistants;
    
    public Induction() {
        this.assistants = new ArrayList<>();
    }

    public Induction(String id, Long startDateTime, Integer capacity, Integer duration) {
        this();
        this.id = id;
        this.startDateTime = startDateTime;
        this.capacity = capacity;
        this.duration = duration;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "startDateTime")
    public Long getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(Long startDateTime) {
        this.startDateTime = startDateTime;
    }

    @DynamoDBAttribute(attributeName = "capacity")
    public Integer getCapacity() {
        return capacity;
    }

    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    @DynamoDBAttribute(attributeName = "duration")
    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    
    @DynamoDBAttribute(attributeName = "assistants")
    public List<String> getAssistants() {
        return assistants;
    }

    public void setAssistants(List<String> assistants) {
        this.assistants = assistants;
    }

    
}
