package com.tuprofe.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author diego
 */
@DynamoDBTable(tableName = "interview")
public class Interview implements Serializable {

    private String id;
    private Long startDateTime;
    private Integer capacity;
    private Integer duration;
    private List<String> interviewed;

    public Interview() {
        this.interviewed = new ArrayList<>();
    }

    public Interview(String id, Long startDateTime, Integer capacity, Integer duration) {
        this();
        this.id = id;
        this.startDateTime = startDateTime;
        this.capacity = capacity;
        this.duration = duration;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "startDateTime")
    public Long getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(Long startDateTime) {
        this.startDateTime = startDateTime;
    }

    @DynamoDBAttribute(attributeName = "capacity")
    public Integer getCapacity() {
        return capacity;
    }

    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    @DynamoDBAttribute(attributeName = "duration")
    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    @DynamoDBAttribute(attributeName = "interviewed")
    public List<String> getInterviewed() {
        return interviewed;
    }

    public void setInterviewed(List<String> interviewed) {
        this.interviewed = interviewed;
    }

}
