package com.tuprofe.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author diego
 */
@DynamoDBTable(tableName = "interview")
public class Interview implements Serializable{

    private String id;
    private Date startDateTime;
    private Integer capacity;
    private Integer duration;

    public Interview() {
    }

    public Interview(String id, Date startDateTime, Integer capacity, Integer duration) {
        this.id = id;
        this.startDateTime = startDateTime;
        this.capacity = capacity;
        this.duration = duration;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "startDateTime")
    public Date getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    @DynamoDBAttribute(attributeName = "capacity")
    public Integer getCapacity() {
        return capacity;
    }

    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    @DynamoDBAttribute(attributeName = "duration")
    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

}
